select 학과명,
	   NVL( SUM( CASE WHEN AGE <= 15 AND 성별 = '남' THEN 1 END ), 0 ) "15세 이하(남)",
	   NVL( SUM( CASE WHEN AGE <= 15 AND 성별 = '여' THEN 1 END ), 0 ) "15세 이하(여)",
	   NVL( SUM( CASE WHEN AGE = 16 AND 성별 = '남' THEN 1 END ), 0 ) "16세(남)",
       NVL( SUM( CASE WHEN AGE = 16 AND 성별 = '여' THEN 1 END ), 0 ) "16세(여)",
       NVL( SUM( CASE WHEN AGE = 17 AND 성별 = '남' THEN 1 END ), 0 ) "17세(남)",
       NVL( SUM( CASE WHEN AGE = 17 AND 성별 = '여' THEN 1 END ), 0 ) "17세(여)",
       NVL( SUM( CASE WHEN AGE = 18 AND 성별 = '남' THEN 1 END ), 0 ) "18세(남)",
       NVL( SUM( CASE WHEN AGE = 18 AND 성별 = '여' THEN 1 END ), 0 ) "18세(여)",
       NVL( SUM( CASE WHEN AGE = 19 AND 성별 = '남' THEN 1 END ), 0 ) "19세(남)",
       NVL( SUM( CASE WHEN AGE = 19 AND 성별 = '여' THEN 1 END ), 0 ) "19세(여)",
       NVL( SUM( CASE WHEN AGE = 20 AND 성별 = '남' THEN 1 END ), 0 ) "20세(남)",
       NVL( SUM( CASE WHEN AGE = 20 AND 성별 = '여' THEN 1 END ), 0 ) "20세(여)",
       NVL( SUM( CASE WHEN AGE = 21 AND 성별 = '남' THEN 1 END ), 0 ) "21세(남)",
       NVL( SUM( CASE WHEN AGE = 21 AND 성별 = '여' THEN 1 END ), 0 ) "21세(여)",
       NVL( SUM( CASE WHEN AGE = 22 AND 성별 = '남' THEN 1 END ), 0 ) "22세(남)",
       NVL( SUM( CASE WHEN AGE = 22 AND 성별 = '여' THEN 1 END ), 0 ) "22세(여)",
       NVL( SUM( CASE WHEN AGE = 23 AND 성별 = '남' THEN 1 END ), 0 ) "23세(남)",
       NVL( SUM( CASE WHEN AGE = 23 AND 성별 = '여' THEN 1 END ), 0 ) "23세(여)",
       NVL( SUM( CASE WHEN AGE = 24 AND 성별 = '남' THEN 1 END ), 0 ) "24세(남)",
       NVL( SUM( CASE WHEN AGE = 24 AND 성별 = '여' THEN 1 END ), 0 ) "24세(여)",
       NVL( SUM( CASE WHEN AGE = 25 AND 성별 = '남' THEN 1 END ), 0 ) "25세(남)",
       NVL( SUM( CASE WHEN AGE = 25 AND 성별 = '여' THEN 1 END ), 0 ) "25세(여)",
       NVL( SUM( CASE WHEN AGE = 26 AND 성별 = '남' THEN 1 END ), 0 ) "26세(남)",
       NVL( SUM( CASE WHEN AGE = 26 AND 성별 = '여' THEN 1 END ), 0 ) "26세(여)",
       NVL( SUM( CASE WHEN AGE = 27 AND 성별 = '남' THEN 1 END ), 0 ) "27세(남)",
       NVL( SUM( CASE WHEN AGE = 27 AND 성별 = '여' THEN 1 END ), 0 ) "27세(여)",
       NVL( SUM( CASE WHEN AGE = 28 AND 성별 = '남' THEN 1 END ), 0 ) "28세(남)",
       NVL( SUM( CASE WHEN AGE = 28 AND 성별 = '여' THEN 1 END ), 0 ) "28세(여)",
       NVL( SUM( CASE WHEN AGE = 29 AND 성별 = '남' THEN 1 END ), 0 ) "29세(남)",
       NVL( SUM( CASE WHEN AGE = 29 AND 성별 = '여' THEN 1 END ), 0 ) "29세(여)",
       NVL( SUM( CASE WHEN AGE >= 30 AND AGE <= 34 AND 성별 = '남' THEN 1 END ), 0 ) "30~34세(남)",
       NVL( SUM( CASE WHEN AGE >= 30 AND AGE <= 34 AND 성별 = '여' THEN 1 END ), 0 ) "30~34세(여)",
       NVL( SUM( CASE WHEN AGE >= 35 AND AGE <= 39 AND 성별 = '남' THEN 1 END ), 0 ) "35~39세(남)",
       NVL( SUM( CASE WHEN AGE >= 35 AND AGE <= 39 AND 성별 = '여' THEN 1 END ), 0 ) "35~39세(여)",
       NVL( SUM( CASE WHEN AGE >= 40 AND AGE <= 49 AND 성별 = '남' THEN 1 END ), 0 ) "40~49세(남)",
       NVL( SUM( CASE WHEN AGE >= 40 AND AGE <= 49 AND 성별 = '여' THEN 1 END ), 0 ) "40~49세(여)",
       NVL( SUM( CASE WHEN AGE >= 50 AND AGE <= 59 AND 성별 = '남' THEN 1 END ), 0 ) "50~59세(남)",
       NVL( SUM( CASE WHEN AGE >= 50 AND AGE <= 59 AND 성별 = '여' THEN 1 END ), 0 ) "50~59세(여)",
       NVL( SUM( CASE WHEN AGE >= 60 AND 성별 = '남' THEN 1 END ), 0 ) "60세 이상(남)",
       NVL( SUM( CASE WHEN AGE >= 60 AND 성별 = '여' THEN 1 END ), 0 ) "60세 이상(여)"
from
(select 학과명, 학번, 성별, age(SUBSTR(주민등록번호,1,6), substr(:조사기준일,1,4) || '0301') age from tm학적_&조사기준일 학적, tm학과 학과
where substr(학적상태,1,1) in ('0', '1') AND 학번 NOT LIKE 'T%'
and 학적.학과코드 = 학과.학과코드)
GROUP BY 학과명