--학년도,학년,학기,학과코드,교과코드)
DELETE FROM tbl강의평가
WHERE 학년도 = :학년도 AND 학기 = :학기;
INSERT INTO TBL강의평가
SELECT A.*
      FROM
           (
SELECT A.SCHOOLYEAR 학년도, A.SEMESTER 학기, F_HGNM(SUBSTR(SUBJECT,1,2)) 학과명, F_USERNM(A.PROFESSOR) 교수명, GM_KNAME 과목명, B.ITEMSHORTNM 설문내용, A.LVL1 아주그렇다,A.LVL2 그렇다,A.LVL3 보통이다,A.LVL4 아니다,A.LVL5 전혀아니다,
		A.AVG_LEV 평점평균, A.SUM_LEV 응답자수,A.AVG_LEV 환산평점
  FROM (

         SELECT SCHOOLYEAR,SEMESTER,PROFESSOR,ITEMCD, SUBJECT,
       S_LVL1 LVL1,
       S_LVL2 LVL2,
       S_LVL3 LVL3,
       S_LVL4 LVL4,
       S_LVL5 LVL5,
       ROUND(((S_LVL1 * 5) + (S_LVL2 * 4) + (S_LVL3 * 3) + (S_LVL4 * 2) + (S_LVL5 * 1)) / SUM_LEV , 2 ) as AVG_LEV,
       SUM_LEV
  FROM
(
    --SELECT  A.SCHOOLYEAR, A.SEMESTER,A.GRADE,A.PROFESSOR, A.SUBJECT, A.ITEMCD,
    SELECT  A.SCHOOLYEAR, A.SEMESTER,A.PROFESSOR, A.SUBJECT, A.ITEMCD,
SUM(A.LEVEL1) S_LVL1,SUM(A.LEVEL2) S_LVL2,SUM(A.LEVEL3) S_LVL3,SUM(A.LEVEL4) S_LVL4,SUM(A.LEVEL5) S_LVL5 ,
SUM(A.LEVEL1) + SUM(A.LEVEL2) + SUM(A.LEVEL3) + SUM(A.LEVEL4) + SUM(A.LEVEL5) SUM_LEV

      FROM
    (
        --SELECT A.SEQNO,A.SCHOOLYEAR, A.GRADE, A.SEMESTER,A.PROFESSOR,
        SELECT A.SEQNO,A.SCHOOLYEAR, A.SEMESTER,A.PROFESSOR,
   A.SUBJECT,B.ITEMCD,B.LEVEL1,B.LEVEL2,B.LEVEL3,B.LEVEL4,B.LEVEL5
          FROM TDEVALUATEHEAD A,TDEVALUATEDTL B
         WHERE A.SEQNO = B.SEQNO
           AND A.SCHOOLYEAR = :학년도
           AND A.SEMESTER = :학기
           --AND A.SUBJECT = :GMCD
     ) A


    --GROUP BY A.SCHOOLYEAR, A.SEMESTER,A.GRADE, A.PROFESSOR,A.ITEMCD, SUBJECT
    GROUP BY A.SCHOOLYEAR, A.SEMESTER,A.PROFESSOR,A.ITEMCD, SUBJECT

) A
        ) A,
        TMITEM B, AC1302
 WHERE A.SCHOOLYEAR = B.SCHOOLYEAR
   AND A.SEMESTER = B.SEMESTER
   AND A.ITEMCD = B.ITEMCD
   AND SUBJECT = GM_CODE
  ORDER BY F_HGNM(SUBSTR(SUBJECT,1,2)), A.PROFESSOR, A.SUBJECT, A.ITEMCD
) A

