SELECT HJ_HAKBUN 학번, HJ_KNAME 성명, HJ_JCODE1 || '-' || HJ_JCODE2 주민번호,
DEPTNAME(HJ_HGCODE) 현학과, DEPTNAME(SUBSTR(HJ_HAKBUN,4,2)) 전학과, HC_SIYMD 전과일자 FROM PSUTIS.AC12011, PSUTIS.AC1202
WHERE HJ_HAKBUN = HC_HAKBUN
AND HC_SCODE = '31' AND HC_SIYMD > '20120301'
ORDER BY HC_SIYMD