SELECT DISTINCT 학자금코드  학과코드, DECODE(hc_scode, '52', '15', '53', '14', '19') 학적코드,
주민등록번호, 학번, 성 || 이름 학생명, 학년,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '30', F_GETDCODE(J.JANGHAKCD1), '') ||
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '30', F_GETDCODE(J.JANGHAKCD2), '') ||
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '30', F_GETDCODE(J.JANGHAKCD3), '') 장학상품코드1,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '30', NVL(J.SCHOLARSHIP1, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '30', NVL(J.SCHOLARSHIP2, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '30', NVL(J.SCHOLARSHIP3, 0), 0) 국가장학금1,
'' 장학상품코드2, 0 국가장학금2, '' 장학상품코드3, 0 국가장학금3,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '10', NVL(J.SCHOLARSHIP1, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '10', NVL(J.SCHOLARSHIP2, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '10', NVL(J.SCHOLARSHIP3, 0), 0) 교내장학금,
0 교외장학금, TUITION 수업료, 0 기성회비, ADMISSIONFEE 입학금
FROM TDFEEGOJI 고지서, TDFEERECEIVE 수납파일, TDJANGHAKSUM J, TM학적 S, TM학과 H,
(SELECT * FROM psutis.AC1202
WHERE HC_SIYMD > DECODE(:학기, '1', :학년도 - 1 || '12', '2', :학년도 || '07')
) C--, TMSCHOLARSHIP C
WHERE 고지서.SCHOOLYEAR = :학년도 AND 고지서.SEMESTER = :학기
AND 고지서.SCHOOLYEAR = J.SCHOOLYEAR(+)
AND 고지서.SEMESTER = J.SEMESTER(+)
AND 고지서.HAKBUN = J.HAKBUN(+)
AND 고지서.HAKBUN = 학번 AND S.학과코드 = H.학과코드
AND 고지서.SCHOOLYEAR = 수납파일.SCHOOLYEAR(+)
AND 고지서.SEMESTER = 수납파일.SEMESTER(+)
AND 고지서.hakbun = 수납파일.HAKBUN(+)
AND 학번 = hc_hakbun(+)
AND 학적상태 = '01'
ORDER BY 학과코드, 학번

