SELECT SCHOOLYEAR 학년도, SEMESTER 학기, HAKBUN 학번, 학과명, JANGHAKNM 장학명, SCHOLARSHIP 금액, '' 비고
FROM TDJANGHAK A, TM학적, TMSCHOLARSHIP B, TM학과 C
WHERE SCHOOLYEAR = '2014' AND SEMESTER = '1'
AND A.JANGHAKCD = B.JANGHAKCD
AND A.HAKBUN = 학번
AND A.CLASS = C.학과코드
AND HAKBUN NOT IN (SELECT HAKBUN FROM TDFEEGOJI WHERE SCHOOLYEAR = '2014' AND SEMESTER = '1'
AND STATE IN ('77', '22') )