SELECT * FROM TDJANGHAK m
WHERE (schoolyear, semester, hakbun)
IN (SELECT schoolyear, semester, hakbun FROM TDJANGHAKSUM d
WHERE d.SCHOOLYEAR = m.SCHOOLYEAR
AND d.SEMESTER = m.SEMESTER
AND d.HAKBUN = m.HAKBUN
AND d.JANGHAKCD1 = m.JANGHAKCD
AND d.GBN1 <> m.GBN)
UNION
SELECT * FROM TDJANGHAK m
WHERE (schoolyear, semester, hakbun)
IN (SELECT schoolyear, semester, hakbun FROM TDJANGHAKSUM d
WHERE d.SCHOOLYEAR = m.SCHOOLYEAR
AND d.SEMESTER = m.SEMESTER
AND d.HAKBUN = m.HAKBUN
AND d.JANGHAKCD2 = m.JANGHAKCD
AND d.GBN2 <> m.GBN)
UNION
SELECT * FROM TDJANGHAK m
WHERE (schoolyear, semester, hakbun)
IN (SELECT schoolyear, semester, hakbun FROM TDJANGHAKSUM d
WHERE d.SCHOOLYEAR = m.SCHOOLYEAR
AND d.SEMESTER = m.SEMESTER
AND d.HAKBUN = m.HAKBUN
AND d.JANGHAKCD3 = m.JANGHAKCD
AND d.GBN3 <> m.GBN)
UNION
SELECT * FROM TDJANGHAK m
WHERE (schoolyear, semester, hakbun)
IN (SELECT schoolyear, semester, hakbun FROM TDJANGHAKSUM d
WHERE d.SCHOOLYEAR = m.SCHOOLYEAR
AND d.SEMESTER = m.SEMESTER
AND d.HAKBUN = m.HAKBUN
AND d.JANGHAKCD4 = m.JANGHAKCD
AND d.GBN4 <> m.GBN)