/* UPDATE TDFEEGOJI AA SET state = (SELECT STATE FROM TDFEERECEIVE bb WHERE
bb.SCHOOLYEAR = aa.SCHOOLYEAR AND bb.SEMESTER = aa.SEMESTER
AND bb.HAKBUN = aa.HAKBUN AND bb.HAKBUN <> 'A1148026' AND bb.state = '77')
WHERE aa.hakbun IN (
SELECT DISTINCT cc.hakbun
FROM TDFEEGOJI cc, TDFEERECEIVE dd
WHERE cc.SCHOOLYEAR = dd.SCHOOLYEAR AND cc.SEMESTER = dd.SEMESTER
AND cc.HAKBUN = dd.HAKBUN
AND cc.state <> dd.STATE
AND dd.hakbun <> 'A1148026'
AND dd.state = '77') */
--SELECT cc.hakbun, cc.state, dd.STATE, cc.
--FROM TDFEEGOJI cc, TDFEERECEIVE dd
--WHERE cc.SCHOOLYEAR = dd.SCHOOLYEAR AND cc.SEMESTER = dd.SEMESTER
--AND cc.HAKBUN = dd.HAKBUN
--AND cc.state <> dd.STATE