UPDATE TM학적 AA SET 성 = (SELECT SUBSTR(HJ_KNAME,1,1) FROM PSUTIS.AC12011 WHERE HJ_HAKBUN = AA.학번),
이름= (SELECT SUBSTR(HJ_KNAME,2) FROM PSUTIS.AC12011 WHERE HJ_HAKBUN = AA.학번)
--SELECT * FROM TM학적
WHERE 학번 IN (
SELECT 학번
FROM TM학적, PSUTIS.AC12011
WHERE 학번 = HJ_HAKBUN
AND 성 || 이름 <> HJ_KNAME
);
