INSERT INTO TMEMPLOYEE
SELECT A.교직원코드,
       A.성,
       A.이름,
       DECODE(SUBSTR(주민번호,7,1),'1', '남', '여'),
       SUBSTR(주민번호,1,6),
       A.주민번호,
       'N' 결혼,
       '001' 국적코드,
       A.우편번호,
       A.지번주소,
       A.상세주소,
       A.집전화,
       A.핸드폰,
       0 부양가족수,
       A.직책코드,
       A.부서코드,
       A.현상태,
       A.임용일자,
       A.퇴직일자,
       A.직급코드,
       A.호봉,
       A.직능코드,
       A.전자우편
  FROM TM인사 A
