SELECT 학자금코드  학과코드, '19' 학적코드, 주민등록번호, 학번, 성 || 이름 학생명, 학년,
'1' 등록금납부대상구분, '20120930' 수납원장마감일자,
'1' 대학수납계좌구분1, '032' 수납계좌은행코드1, F_GETVNO(학번, '301002') 수납은행계좌번호1, 성 || 이름 수납계좌예금주명1,
'1' 대학수납계좌구분2, '011' 수납계좌은행코드2, F_GETVNO(학번, '301003') 수납은행계좌번호2, 성 || 이름 수납계좌예금주명2,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '30', F_GETDCODE(J.JANGHAKCD1), '') ||
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '30', F_GETDCODE(J.JANGHAKCD2), '') ||
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '30', F_GETDCODE(J.JANGHAKCD3), '') 장학상품코드1,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '30', NVL(J.SCHOLARSHIP1, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '30', NVL(J.SCHOLARSHIP2, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '30', NVL(J.SCHOLARSHIP3, 0), 0) 국가장학금1,
'' 장학상품코드2, '' 국가장학금2, '' 장학상품코드3, '' 국가장학금3,
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD1), '10', NVL(J.SCHOLARSHIP1, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD2), '10', NVL(J.SCHOLARSHIP2, 0), 0) +
DECODE(F_GETJANGHAKGBN(J.JANGHAKCD3), '10', NVL(J.SCHOLARSHIP3, 0), 0) 교내장학금,
0 교외장학금, ADMISSIONFEE 입학금, TUITION 수업료, '' 기성회비
FROM TDFEEGOJI D, TDJANGHAKSUM J, TM학적 S, TM학과 H --, TMSCHOLARSHIP C
WHERE D.SCHOOLYEAR = J.SCHOOLYEAR(+)
AND D.SEMESTER = J.SEMESTER(+)
AND D.HAKBUN = J.HAKBUN(+)
AND D.HAKBUN = 학번 AND S.학과코드 = H.학과코드

