SELECT DISTINCT gmkname, gmename FROM TMGWAMOK A
--UPDATE TMGWAMOK A SET GMENAME = (SELECT TRIM(GMENAME) FROM TMEGWAMOK S WHERE S.GMKNAME = A.GMKNAME)
WHERE A.GMENAME IS NULL
--AND A.GMKNAME IN (SELECT GMKNAME FROM TMEGWAMOK);
--AND REPLACE(A.GMKNAME, ' ', '') IN (SELECT REPLACE(GM_KNAME,' ', '') FROM AC1302 WHERE gm_ename IS NOT NULL or gm_ename <> '1');




